# Generated by Django 3.0.5 on 2020-05-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgames', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='games',
            field=models.ManyToManyField(related_name='players', to='cardgames.Game'),
        ),
    ]
